### PR TITLE
Small accessability change

### PR DESCRIPTION
**Pull request by SirEpiclyAmazing**

### CODE REVIEW

**Comment by Jonfirexbox** [comment]
you didn't really change anything

**Comment by Hadimhz** [comment]
i fail to see what changed.... the code you added at the top is commented

**Comment by Jonfirexbox** [comment]
> i fail to see what changed.... the code you added at the top is commented

so this just means this pr has no purpose

**Comment by freddierick** [comment]
I personally like it and think danbot should have more PRs like this.
They are very easy to code review!

**Comment by itzJOHv** [comment]
> I personally like it and think danbot should have more PRs like this.
> They are very easy to code review!

bruh

**Comment by freddierick** [comment]
@Hadimhz merge it

**Comment by Jonfirexbox** [comment]
> @Hadimhz merge it

did you even see what the person did they just changed some of the backslashes around

**Pull request closed without merging**
